[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"

[[redirects]]
  # SPA pages (as rewrites) to top page
  from = "/v3/entry/github/*"
  to = "/index.html"
  status = 200

[[redirects]]
  # 404 pages we wont handle
  from = "/404"
  to = "/404.html"
  status = 404

[build]
  publish = "public"
  command = "./deno2node"
